### ISSUE TITLE
Add golangci linter to make lint target

### ISSUE THREAD

**Issue by austinvazquez** [awslabs/tc-redirect-tap#19]
Today's `make lint` does nothing. I'd like to at least do a spot check using golangci-lint.

**Comment by u5surf** [comment]
@austinvazquez Hi, I’d like to work on this issue. What should we use the linter rules about this? we consider that it makes suitable for us to regulate some rules instead of using —enable-all.

**Comment by austinvazquez** [comment]
@u5surf, I don't have any arguments against enable all at this point in time. The code base is fairly small and not too opinionated so issues are easy to fix still.

**Comment by austinvazquez** [comment]
@u5surf, ah that is my mistake. In that case, let's not run with `--enable-all`. `golangci-lint run` should be enough and which will exclude the deprecated linters.

**Comment by austinvazquez** [comment]
Issue resolved with #25. Thanks @u5surf for the work to close this.
